file_length:
  warning: 500
  error: 800
  
function_body_length:
  warning: 150
  error: 200

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - x
    - y
    - z

line_length:
  warning: 200
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level: 1

type_body_length:
  warning: 300
  error: 400

disabled_rules:

excluded:
  - .build               # SPM 빌드 캐시 전체
  - Packages             # SPM 매니페스트 디렉토리
  - "**/checkouts/**"    # 체크아웃된 모든 SPM 패키지 코드
